manifest:
  defaults:
    remote: zmkfirmware

  remotes:
    - name: zmkfirmware
      url: https://github.com/zmkfirmware
    - name: zephyrproject
      url: https://github.com/zephyrproject-rtos

  projects:
    - name: zmk
      repo-path: zmk
      revision: main
      import:
        path-prefix: deps
        projects:
          - name: zephyr
            remote: zephyrproject
            revision: main
            import: true

  self:
    path: config