# GitHub Actions Workflow (From ergomechstore)
name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip ninja-build cmake gcc-arm-none-eabi gperf
          pip3 install "west>=1.3.0"
          west init -l config
          west update
          west zephyr-export
          pip3 install -r zephyr/scripts/requirements.txt

      - name: Build Left
        run: |
          west build -s app -b nice_nano_v2 -- -DSHIELD=sofle_left -DZMK_CONFIG="$(pwd)/config"

      - name: Build Right
        run: |
          west build -s app -b nice_nano_v2 -- -DSHIELD=sofle_right -DZMK_CONFIG="$(pwd)/config"

      - name: Install Keymap Drawer
        run: |
          pip install keymap-drawer

      - name: Generate Keymap SVG
        run: |
          keymap-drawer draw config/boards/shields/sofle/keymap.keymap -o output/
