name: Build ZMK Firmware + Generate Keymap

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZEPHYR_TOOLCHAIN_VARIANT: gnuarmemb
    steps:
      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y ninja-build gperf ccache dfu-util device-tree-compiler wget python3-pip python3-setuptools python3-wheel xz-utils file make gcc-arm-none-eabi
          pip3 install "west>=1.3.0" keymap-drawer

      - name: Clone ZMK
        run: |
          west init -m https://github.com/zmkfirmware/zmk.git --mr main zmk
          cd zmk
          west update
          west zephyr-export
          pip3 install -r zephyr/scripts/requirements.txt

      - name: Copy user config
        run: |
          cp -r ../config ./config

      - name: Build left
        working-directory: zmk/app
        run: |
          west build -s . -b nice_nano_v2 -- -DSHIELD=sofle_left -DZMK_CONFIG=../config

      - name: Build right
        working-directory: zmk/app
        run: |
          west build -s . -b nice_nano_v2 -- -DSHIELD=sofle_right -DZMK_CONFIG=../config

      - name: Generate Keymap SVG
        run: |
          mkdir -p output/keymap
          keymap-drawer draw config/boards/shields/sofle/keymap.keymap -o output/keymap/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Firmware-and-Keymap
          path: |
            zmk/app/build/zephyr/zmk.uf2
            output/keymap/