name: Build ZMK Firmware + Generate Keymap

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZEPHYR_TOOLCHAIN_VARIANT: gnuarmemb
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build gperf ccache dfu-util device-tree-compiler wget python3-pip python3-setuptools python3-wheel xz-utils file make gcc-arm-none-eabi
          pip3 install "west>=1.3.0" keymap-drawer

      - name: Clone ZMK fork (sofle-v2-oled-zmk)
        run: |
          mkdir zmk-workspace
          cd zmk-workspace
          git clone --depth 1 https://github.com/ergomechstore/sofle-v2-oled-zmk.git firmware
          cd firmware
          west init -l app
          west update
          west zephyr-export
          pip3 install -r zephyr/scripts/requirements.txt

      - name: Copy user config into firmware
        run: |
          cp -r config zmk-workspace/firmware/app/config

      - name: Build left side
        working-directory: zmk-workspace/firmware/app
        run: |
          west build -s . -b nice_nano_v2 -- -DSHIELD=sofle_left -DZMK_CONFIG=./config
          mkdir -p ../../../output
          cp build/zephyr/zmk.uf2 ../../../output/sofle_left.uf2

      - name: Build right side
        working-directory: zmk-workspace/firmware/app
        run: |
          west build -s . -b nice_nano_v2 -- -DSHIELD=sofle_right -DZMK_CONFIG=./config
          cp build/zephyr/zmk.uf2 ../../../output/sofle_right.uf2

      - name: Generate Keymap Drawer SVG
        run: |
          mkdir -p output/keymap
          keymap-drawer draw config/boards/shields/sofle/keymap.keymap -o output/keymap/

      - name: Upload Firmware and Keymap
        uses: actions/upload-artifact@v4
        with:
          name: zmk-firmware-and-keymap
          path: |
            output/sofle_left.uf2
            output/sofle_right.uf2
            output/keymap/