name: Build ZMK Firmware + Keymap

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install West and Python deps
        run: |
          pip install west
          pip install pykwalify

      - name: Create ZMK Workspace
        run: |
          mkdir zmk-workspace
          cd zmk-workspace
          west init -l ..
          west update

      - name: Build Left Half
        run: |
          cd zmk-workspace
          west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=sofle_left -DZMK_CONFIG="$(realpath ../config)"

      - name: Move Left Firmware
        run: |
          mkdir -p output
          cp zmk-workspace/build/zephyr/zmk.uf2 output/sofle_left.uf2

      - name: Build Right Half
        run: |
          cd zmk-workspace
          west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=sofle_right -DZMK_CONFIG="$(realpath ../config)"

      - name: Move Right Firmware
        run: |
          mkdir -p output
          cp zmk-workspace/build/zephyr/zmk.uf2 output/sofle_right.uf2

      - name: Generate Keymap JSON
        run: |
          cd zmk-workspace
          west build -s zmk/app -t output-keymap

      - name: Move Keymap JSON
        run: |
          mkdir -p output
          cp zmk-workspace/build/zephyr/zmk-keymap.json output/keymap.json

      - name: Upload Firmware and Keymap
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: output/